# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- ToDoListAPI

pool:
  name: Default
  demands:
    - agent.name -equals VM-ToDoList-Dev

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    if ! command -v dotnet &> /dev/null
    then
      echo ".NET SDK not found. Installing..."
      sudo apt update
      sudo apt install -y wget apt-transport-https software-properties-common
      wget https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb
      sudo dpkg -i packages-microsoft-prod.deb
      sudo apt update
      sudo apt install -y dotnet-sdk-8.0
    else
      echo ".NET SDK already installed: $(dotnet --version)"
    fi
  displayName: 'Check and Install .NET SDK if Missing'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
