trigger:
- master  # Changed from 'main' to 'master'

variables:
  buildConfiguration: 'Release'
  solutionPath: 'ToDoList.API/ToDoList.API.sln'  # Path to your solution
  projectPath: 'ToDoList.API/ToDoList.API.csproj'  # Path to your project

pool:
  name: Default

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    version: '8.0.x'

- script: dotnet restore $(solutionPath)
  displayName: 'Restore NuGet packages'
  workingDirectory: $(Build.SourcesDirectory)  # Explicitly set working directory

- script: dotnet build $(solutionPath) --configuration $(buildConfiguration) --no-restore
  displayName: 'Build solution'
  workingDirectory: $(Build.SourcesDirectory)

- script: dotnet publish $(Build.SourcesDirectory)/ToDoList.API/ToDoList.API.csproj -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Publish API'
  workingDirectory: $(Build.SourcesDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'